CREATE TABLE jobs (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	max_salary numeric(15, 3) NOT NULL,
	min_salary numeric(15, 3) NULL,
	"name" varchar(100) NOT NULL,
	CONSTRAINT jobs_pkey PRIMARY KEY (id),
	CONSTRAINT jobs_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

CREATE TABLE locations (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	city varchar(100) NOT NULL,
	street_address varchar(255) NOT NULL,
	CONSTRAINT locations_pkey PRIMARY KEY (id),
	CONSTRAINT locations_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

CREATE TABLE refresh_tokens (
	id uuid NOT NULL,
	expires_at timestamptz(6) NOT NULL,
	grant_id int4 NOT NULL,
	iat timestamptz(6) NOT NULL,
	CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id)
);

CREATE TABLE roles (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	description varchar(50) NULL,
	"role" varchar(255) NOT NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (id),
	CONSTRAINT roles_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[]))),
	CONSTRAINT roles_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

CREATE TABLE sessions (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	destroyed_at timestamp(6) NULL,
	expired_at int8 NOT NULL,
	"json" varchar(255) NOT NULL,
	CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE attendance_logs (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	check_in_time time(6) NULL,
	check_out_time time(6) NULL,
	log_date date NULL,
	status varchar(255) NULL,
	employee_id int4 NULL,
	CONSTRAINT attendance_logs_pkey PRIMARY KEY (id),
	CONSTRAINT attendance_logs_status_check CHECK (((status)::text = ANY ((ARRAY['Present'::character varying, 'Absent'::character varying, 'Leave'::character varying, 'Late'::character varying, 'Half_day'::character varying])::text[]))),
	CONSTRAINT ukfknfp4eqsdmixd20vuhc7erm2 UNIQUE (employee_id, log_date)
);

CREATE TABLE departments (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	"name" varchar(100) NOT NULL,
	location_id int4 NOT NULL,
	manager_id int4 NULL,
	CONSTRAINT departments_pkey PRIMARY KEY (id),
	CONSTRAINT departments_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))),
	CONSTRAINT ukn6rq9sdwiiio8v8gn6n9cgqlx UNIQUE (manager_id)
);

CREATE TABLE employees (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	email varchar(100) NOT NULL,
	first_name varchar(100) NOT NULL,
	hire_date date NOT NULL,
	last_name varchar(100) NULL,
	phone_number varchar(50) NULL,
	salary numeric(15, 3) NOT NULL,
	department_id int4 NULL,
	job_id int4 NOT NULL,
	manager_id int4 NULL,
	CONSTRAINT employees_pkey PRIMARY KEY (id),
	CONSTRAINT employees_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))),
	CONSTRAINT ukj9xgmd0ya5jmus09o0b8pqrpb UNIQUE (email)
);

CREATE TABLE job_history (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	end_date date NULL,
	start_date date NOT NULL,
	department_id int4 NOT NULL,
	employee_id int4 NOT NULL,
	job_id int4 NOT NULL,
	CONSTRAINT job_history_pkey PRIMARY KEY (id),
	CONSTRAINT job_history_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

CREATE TABLE user_roles (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	role_id int4 NOT NULL,
	user_id int4 NOT NULL,
	CONSTRAINT user_roles_pkey PRIMARY KEY (id),
	CONSTRAINT user_roles_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

CREATE TABLE users (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	"password" varchar(100) NOT NULL,
	username varchar(100) NOT NULL,
	employee_id int4 NOT NULL,
	CONSTRAINT ukd1s31g1a7ilra77m65xmka3ei UNIQUE (employee_id),
	CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


-- public.attendance_logs foreign keys

ALTER TABLE public.attendance_logs ADD CONSTRAINT fkjt6lbm029cv43dj7iaukcg5v3 FOREIGN KEY (employee_id) REFERENCES employees(id);


-- public.departments foreign keys

ALTER TABLE public.departments ADD CONSTRAINT fk56q3esufky8u69xbmo4n63c4r FOREIGN KEY (manager_id) REFERENCES employees(id);
ALTER TABLE public.departments ADD CONSTRAINT fkqsrwrq8xt10jqu1jjwpdnvnno FOREIGN KEY (location_id) REFERENCES locations(id);


-- public.employees foreign keys

ALTER TABLE public.employees ADD CONSTRAINT fkgy4qe3dnqrm3ktd76sxp7n4c2 FOREIGN KEY (department_id) REFERENCES departments(id);
ALTER TABLE public.employees ADD CONSTRAINT fki4365uo9af35g7jtbc2rteukt FOREIGN KEY (manager_id) REFERENCES employees(id);
ALTER TABLE public.employees ADD CONSTRAINT fknpqyu6u0fdh2rmqtoue23gxb4 FOREIGN KEY (job_id) REFERENCES jobs(id);


-- public.job_history foreign keys

ALTER TABLE public.job_history ADD CONSTRAINT fk6wr8te1t0a1gqbfkfgtqhhkqf FOREIGN KEY (job_id) REFERENCES jobs(id);
ALTER TABLE public.job_history ADD CONSTRAINT fk7y43ipy5e5g2jd2vaiskn76c9 FOREIGN KEY (department_id) REFERENCES departments(id);
ALTER TABLE public.job_history ADD CONSTRAINT fkhbqeamoyj90wvkw4a25camb4n FOREIGN KEY (employee_id) REFERENCES employees(id);


-- public.user_roles foreign keys

ALTER TABLE public.user_roles ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES roles(id);
ALTER TABLE public.user_roles ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES users(id);


-- public.users foreign keys

ALTER TABLE public.users ADD CONSTRAINT fk6p2ib82uai0pj9yk1iassppgq FOREIGN KEY (employee_id) REFERENCES employees(id);